### ISSUE TITLE
Tämä tavuttuu väärin: tekijänoikeusjärjestö

### ISSUE THREAD

**Issue by Ciantic** [vepasto/finnish-hyphenator#3]
tekijänoikeusjärjestö tavuttuu nyt näin: te-ki-jä-noi-keus-jär-jes-tö, sen pitäs ehkä olla te-ki-jän...

Onkohan tuota "voikko" tavutinta javascriptinä, ei taida olla ihan helppo homma tämä tavutus.

```
	FinnishHyphenator.prototype.addHyphen = function(text, idx) {
		var firstPart = text.slice(0, idx);
		if (this.endReg.exec(firstPart)) {
			if (text[idx - 1] == "ä" && text[idx] == "n") {
				return false;
			}
			return (text.slice(0, idx) + this.hyphMark + text.slice(idx));
		} else {
			return false;
		}
	};
```

Tein tuollasen häksin, saa varastaa, public domain!

**Comment by vepasto** [comment]
Tämän kirjaston tarkoitus on olla nopea, kevyt ja toimia lähes kaikissa tapauksissa, sen ei ole tarkoitus olla täydellinen ja se noudattaakin vain yhtä tavutussääntöä.

Kattavampia tavutuskirjastoja löytyy vaikka kuinka, mutta useimpiin tilanteisiin nopea ja pieni kirjasto on parempi.
