### ISSUE TITLE
Bower package nimessä välilyöntejä

### ISSUE THREAD

**Issue by walpek** [vepasto/finnish-hyphenator#6]
Välilyönnit Bower-paketin nimessä aiheuttavat ongelmia.

**Comment by vepasto** [comment]
Jos kerkeät, tee pull request :)

**Comment by vepasto** [comment]
@walpek nyt korjattu. Pitääköhän paketti ilmoittaa sinne uudelleen tms.?

**Comment by walpek** [comment]
@vepasto aika heikosti tuntuu olevan Bowerilla mitään dokumentaatiota vastaavasta tilanteesta.

Uskoisin, että vaatii ainakin uuden releasen tänne Githubin niin saadaan toi muutos Bower installien mukana kulkeviin paketteihin.

Ja jos se ei riitä niin voi olla että pitää ottaa yhteyttä Bowerin tiimiin ja ne sitten hoitaa siellä päässä homman kuntoon.

**Comment by walpek** [comment]
@vepasto voitko tehdä uuden releasen missä tämä paketin nimi on korjattuna :)

**Comment by vepasto** [comment]
Tehty! Tein siitä nyt sit version 1.0.0 koska nimi muuttui.

**Comment by peksipatongeis** [comment]
Jees, nyt toimii 👍
